tetriX: /home/martin/Documents/Universidad/ITBA/2019 - Segundo Cuatrimestre/Programación 1/Practicas/TPF/tetriX/src/frontend/allegro/screen/menu.h File Reference
menu.h File Reference
Main menu when running with Allegro.
#include "../alcontrol.h"
Data Structures
struct menu_t
Main Menu structure.
Enumerations
enum menu_options { NONE = 0, PLAY, ABOUT, EXIT }
Options displayed in Main Menu screen.
Functions
int alg_menu (allegro_t *alStru)
Display game menu.
Detailed Description
Main menu when running with Allegro.
Displays the main menu to the user
Author
Gino Minnucci gminn.nosp@m.ucci.nosp@m.@itba.nosp@m..edu.nosp@m..ar
Martín E. Zahnd mzahn.nosp@m.d@it.nosp@m.ba.ed.nosp@m.u.ar
Date
17/12/2019, 12:26
Copyright
GNU General Public License v3
Enumeration Type Documentation
menu_options
enum menu_options
Options displayed in Main Menu screen.
Enumerator
NONE
Invalid option.
PLAY
Play.
ABOUT
About.
EXIT
Exit game.
Function Documentation
alg_menu()
int alg_menu (allegro_t * alStru)
Display game menu.
Draws the main menu, as well as the about and exit screens
Parameters
alStru Structure with an already initialized display and system
Returns
AL_OK if everything is fine
AL_ERROR if something failed
References ABOUT, AL_ERROR, AL_OK, alg_destroy(), alg_game(), ALLEGRO_MGMT::display, EXIT, ALLEGRO_MGMT::fx, ALLEGRO_MGMT::music, NONE, and PLAY.
Referenced by allegro().