/******************************************************************************
 * Copyright (C) 2019 Martín E. Zahnd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/

/**
 * 
 * @file    test_boardTimer.c
 * 
 * @brief   ;
 * 
 * @details CUnit Test Suite
 * 
 * @authors Gino Minnucci                               <gminnucci@itba.edu.ar>
 *          Martín E. Zahnd                                <mzahnd@itba.edu.ar>
 * 
 * @date    13/12/2019, 17:11
 *
 * @copyright GNU General Public License v3
 */

/// @publicsection
// === Libraries and header files ===
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>        // bool, true, false
#include <time.h>           // clock, CLOCKS_PER_SEC, clock_t, nanosleep
#include <CUnit/Basic.h>

// Functions to test
#include "../src/backend/board/timer/boardTimer.h"

// For STATS structure
#include "../src/backend/stats/stats_mgmt.h"

// === Constants and Macro definitions ===

#define MS2US(t)        ((t) * 1000)

// === Enumerations, structures and typedefs ===

// === Global variables ===

// === Function prototypes for private functions with file level scope ===
int init_suite (void);
int clean_suite (void);

void test1 (void);
void test2 (void);

static void
callTimer (int ms, bool * ans);

static void
testLevel (int limit, int ms);

// === ROM Constant variables with file level scope ===

// === Static variables and constant variables with file level scope ===

// === Global function definitions ===
static stats_t stats;

// Code automatically generated by NetBeans

int
main ()
{
    CU_pSuite pSuite = NULL;

    /* Initialize the CUnit test registry */
    if ( CUE_SUCCESS != CU_initialize_registry() )
        return CU_get_error();

    /* Add a suite to the registry */
    pSuite = CU_add_suite("test_boardTimer", init_suite, clean_suite);
    if ( NULL == pSuite )
    {
        CU_cleanup_registry();
        return CU_get_error();
    }

    /* Add the tests to the suite */
    if ( (NULL == CU_add_test(pSuite, "test1", test1)) ||
         (NULL == CU_add_test(pSuite, "test2", test2)) )
    {
        CU_cleanup_registry();
        return CU_get_error();
    }

    /* Run all tests using the CUnit Basic interface */
    CU_basic_set_mode(CU_BRM_VERBOSE);
    CU_basic_run_tests();
    CU_cleanup_registry();
    return CU_get_error();
}

// === Suite definitions ===

int
init_suite (void)
{
    if ( initStats(&stats) )
    {
        return 1;
    }
    if ( initTimer(&stats) )
    {
        return 1;
    }

    return 0;
}

int
clean_suite (void)
{
    return 0;
}

// Tests definitions ===

void
test1 (void)
{
    CU_PASS("Test not in use.");
    /*stats.level = 1;

    testLevel(9, 100);*/
}

void
test2 (void)
{
    CU_PASS("Test not in use.");
    /*int i;

    for ( i = 1; i < 20; i++ )
    {
        stats.level = i;
        startTimer();
        while ( askTimer() == false );
    }

    stats.level = 20;
    testLevel(2, 100);

    stats.level = 21;
    testLevel(2, 80);*/
}


// === Local function definitions ===

static void
callTimer (int ms, bool * ans)
{
    double dt = 0.0;
    clock_t t0 = clock();

    do
    {
        dt = ((double) (clock() - t0)) / CLOCKS_PER_SEC * 1000.0;
    } while ( dt < ms );

    *ans = askTimer();
}

static void
testLevel (int limit, int ms)
{
    int i;
    bool ans = true;

    startTimer();

    for ( i = 0; i < limit; i++ )
    {
        callTimer(ms, &ans);
        CU_ASSERT(ans == false);
    }

    callTimer(ms, &ans);
    CU_ASSERT(ans == true);
}
