/******************************************************************************
 * Copyright (C) 2019 Martín E. Zahnd
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/

/**
 * 
 * @file    test_random_gen.c
 * 
 * @authors Gino Minnucci                               <gminnucci@itba.edu.ar>
 *          Martín E. Zahnd                                <mzahnd@itba.edu.ar>
 * 
 * @date    28/11/2019, 11:07
 * 
 * @brief   ;
 * 
 * @details CUnit Test Suite
 * 
 * @copyright GNU General Public License v3
 */

/// @publicsection
// === Libraries and header files ===
#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>

// Functions to test
#include "../../src/backend/board/random_generator.h"


// === Constants and Macro definitions ===
// Remember to edit this constants here as well as in .c file
#define MAX_SZ      4
#define MAX_I       12

// === Enumerations, structures and typedefs ===

// === Global variables ===
int num_i;
char rnd_bag[NUM_PIECES];

// === Function prototypes for private functions with file level scope ===
int init_suite (void);
int clean_suite (void);

void test1 (void);
void test2 (void);

static void
print_arr (char arr[NUM_PIECES]);

// === ROM Constant variables with file level scope ===

// === Static variables and constant variables with file level scope ===

// === Global function definitions ===

// Code generated by NetBeans

int
main ()
{
    CU_pSuite pSuite = NULL;

    /* Initialize the CUnit test registry */
    if ( CUE_SUCCESS != CU_initialize_registry() )
        return CU_get_error();

    /* Add a suite to the registry */
    pSuite = CU_add_suite("test_random_gen", init_suite, clean_suite);
    if ( NULL == pSuite )
    {
        CU_cleanup_registry();
        return CU_get_error();
    }

    /* Add the tests to the suite */
    if ( (NULL == CU_add_test(pSuite, "test1", test1)) ||
         (NULL == CU_add_test(pSuite, "test2 (1) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (2) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (3) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (4) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (5) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (6) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (7) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (8) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (9) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (10) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (11) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (12) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (13) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (14) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (15) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (16) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (17) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (18) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (19) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (20) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (21) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (22) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (23) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (24) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (25) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (26) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (27) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (28) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (29) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (30) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (31) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (32) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (33) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (34) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (35) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (36) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (37) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (38) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (39) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (40) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (41) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (42) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (43) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (44) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (45) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (46) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (47) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (48) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (49) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (50) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (51) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (52) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (53) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (54) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (55) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (56) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (57) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (58) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (59) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (60) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (61) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (62) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (63) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (64) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (65) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (66) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (67) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (68) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (69) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (70) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (71) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (72) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (73) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (74) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (75) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (76) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (77) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (78) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (79) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (80) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (81) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (82) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (83) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (84) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (85) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (86) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (87) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (88) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (89) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (90) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (91) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (92) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (93) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (94) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (95) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (96) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (97) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (98) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (99) ", test2)) ||
         (NULL == CU_add_test(pSuite, "test2 (100) ", test2)) )
    {
        CU_cleanup_registry();
        return CU_get_error();
    }

    /* Run all tests using the CUnit Basic interface */
    CU_basic_set_mode(CU_BRM_VERBOSE);
    CU_basic_run_tests();
    CU_cleanup_registry();
    return CU_get_error();
}

// === Suite definitions ===

int
init_suite (void)
{
    if ( init_random_generator() )
    {
        return 1;
    }

    return 0;
}

int
clean_suite (void)
{
    return 0;
}

// === Tests definitions ===

void
test1 ()
{
    int i;
    int count_i, count_j, count_l, count_o,
            count_s, count_t, count_z, count_oth;

    count_oth = 0;
    count_i = count_j = count_l = count_o = count_s = count_t = count_z = 0;

    random_generator(rnd_bag, NUM_PIECES);

    for ( i = 0; i < NUM_PIECES; i++ )
    {
        CU_ASSERT(rnd_bag[i]);

        switch ( rnd_bag[i] )
        {
            case PIECE_I:
                count_i++;
                break;

            case PIECE_J:
                count_j++;
                break;

            case PIECE_L:
                count_l++;
                break;

            case PIECE_O:
                count_o++;
                break;

            case PIECE_S:
                count_s++;
                break;

            case PIECE_T:
                count_t++;
                break;

            case PIECE_Z:
                count_z++;
                break;

            default:
                count_oth++;
                break;
        }
    }

    CU_ASSERT_FALSE(count_oth);

    if ( count_s + count_z > MAX_SZ )
    {
        CU_FAIL("More than MAX_SZ S/Z pieces in the same bag.");
    }

}

void
test2 ()
{
    int i;
    int count_sz = 0;

    char old_bag[NUM_PIECES];

    for ( i = 0; i < NUM_PIECES; i++ )
    {
        old_bag[i] = rnd_bag[i];
    }

    random_generator(rnd_bag, NUM_PIECES);

    puts("\nold_bag: ");
    print_arr(old_bag);

    puts("rnd_bag: ");
    print_arr(rnd_bag);

    for ( i = 0; i < NUM_PIECES; i++ )
    {
        if ( old_bag[i] == PIECE_S || old_bag[i] == PIECE_Z )
        {
            count_sz++;
        }

        else
        {
            count_sz = 0;
        }

        if ( old_bag[i] == PIECE_I )
        {
            num_i = 0;
        }
        else
        {
            num_i++;
        }
    }

    for ( i = 0; i < NUM_PIECES; i++ )
    {
        if ( rnd_bag[i] == PIECE_S || rnd_bag[i] == PIECE_Z )
        {
            count_sz++;
        }

        else
        {
            count_sz = 0;
        }

        if ( rnd_bag[i] == PIECE_I )
        {
            num_i = 0;
        }
        else
        {
            num_i++;
        }
    }

    if ( num_i > MAX_I )
    {
        CU_FAIL("There are more than 12 non I pieces between two I.");
    }

    if ( count_sz > MAX_SZ )
    {
        CU_FAIL("There are more than MAX_SZ S/Z pieces in a row.")
    }

}

// === Local function definitions ===

static void
print_arr (char arr[NUM_PIECES])
{
    int i;

    for ( i = 0; i < NUM_PIECES; i++ )
    {
        printf("%c ", arr[i]);
    }
    putchar('\n');
}
